### PR TITLE
Fix BLUEPILL_F103C6 definition

### PR DESCRIPTION
**Pull request by fpistm**
Hi  @BennehBoy,
I've made some update in order to avoid further issue.
Number of peripheral is not the same between STM32F103C6 and CB
C6 does not have USART3 and TIM4.

I've also rename variant to BLUEPILL_F103XX to avoid any confusion

Note that I will have to rename it also for black pill variant name in boards.txt

### CODE REVIEW

**Comment by BennehBoy** [comment]
@fpistm, not sure what to do with this, I rebased my repo and now this is showing conflicts - I can't see any, so do I just force merge?

**Comment by fpistm** [comment]
Argh. How do you rebase?
In fact you had only to merge my PR on your branch without doing a sync on master. Now, I will have to see how handle this. I will write a contributing.md with a wow and best practice.

**Comment by BennehBoy** [comment]
Yeah sorry I'm a noob.

I added the main repo as upstream
fetch upstream
checkout master
rebase upstream/master
pull
push
then checkout each branch and rebase against my master - fixing conflicts as I go.

If there's a better way I'm all ears, it's a pain as it is.

**Comment by BennehBoy** [comment]
@fpistm this is the process I followed -> https://stackoverflow.com/questions/8948803/what-does-git-remote-add-upstream-help-achieve

It does make a bit of a mess since my PR's include all the upstream/master commits since I first created them.

**Comment by fpistm** [comment]
@BennehBoy 
In fact the beginning of the process is fine but where you do a mistake is on the 2 last step pull and push.
When you rebase your master (the one on the fork) you have to push it on your fork then you are aligned.
Then you can rebase your branch on the master (after resolving conflict if any).

I've push a contributing guideline today:
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/CONTRIBUTING.md

**Comment by fpistm** [comment]
Assuming this:
```
$ git remote -v
ben     https://github.com/BennehBoy/Arduino_Core_STM32 (fetch)
ben     https://github.com/BennehBoy/Arduino_Core_STM32 (push)
stm32duino      https://github.com/stm32duino/Arduino_Core_STM32.git (fetch)
stm3dduino      https://github.com/stm32duino/Arduino_Core_STM32.git (push)
```
So `stm32duino `is original repo and `ben `your fork

What you can do:
1 - Sync your fork master to original repo
```
git checkout stm32duino/master -B master
git push -f ben
```
2 - Then we will rebase your branch
```
git checkout ben/bluepillC6 -B bluepillC6
git rebase -i master
```
You should have an editor open with something like this:
```
pick 7b6f8042 New Variant BluePill F103C6 (32K)
pick 95fe72ea Fix typos
pick 73b225f7 Correct end of stack in linker
pick 63fb0e32 New Variant BluePill F103C6 (32K)
pick 344c0c4f Fix typos
pick 085a1399 Correct end of stack in linker
```
Delete the 3 first commit then save and quit.
Note that you can squash the 3 commits by replacing `pick `by `squash `or `s` ;)
```
pick 63fb0e32 New Variant BluePill F103C6 (32K)
s 344c0c4f Fix typos
s 085a1399 Correct end of stack in linker
```
This will rebase your branch on top of the master.
Well now you will only have to push forced this branch on your fork
`git push -f ben `

That's all folks ;)
Then I will rebase mine if needed.

**Comment by BennehBoy** [comment]
Hmm did all that, it's certainly cleaner - I had to pull after this line to get the new changes from upstream though:

> git checkout stm32duino/master -B master

your repo is 'upstream' in my remote list:

```
$ git remote -v
origin  https://github.com/BennehBoy/Arduino_Core_STM32.git (fetch)
origin  https://github.com/BennehBoy/Arduino_Core_STM32.git (push)
upstream        https://github.com/stm32duino/Arduino_Core_STM32.git (fetch)
upstream        https://github.com/stm32duino/Arduino_Core_STM32.git (push)

```
It now appears worse...  I can't see what the conflicts are though?

**Comment by fpistm** [comment]
This is ok now.
Nice work 👍 

Note: Right I forget to tell you to pull or fetch the original repo before made all the stuff.

**Pull request merged**
